{{ if and (.Values.postgresBackup.enabled) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: waldur-db-backup-rotation-script
data:
  backup-rotation: |-
    #!/bin/bash
    set -e

    export MINIO_PG_BACKUPS_DIR=pg/$MINIO_BUCKET/backups/postgres
    export MAX_BACKUPS_NUMBER={{ .Values.postgresBackup.maxNumber }}

    echo "[+] MINIO_PG_BACKUPS_DIR: $MINIO_PG_BACKUPS_DIR"

    echo "[+] Setting up the postgres alias for minio server ($MINIO_SERVER)"
    mc alias set pg "$MINIO_SERVER" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" --api "$MINIO_API_VERSION" > /dev/null

    export BACKUPS_NUMBER=$(mc find $MINIO_PG_BACKUPS_DIR -name "*.sql.gz" | wc -l)
    export EXTRA_BACKUPS_NUMBER=$(( $BACKUPS_NUMBER - $MAX_BACKUPS_NUMBER ))

    echo "[+] Total number of fresh backups : $BACKUPS_NUMBER"
    echo "[+] Maximum number of backups     : $MAX_BACKUPS_NUMBER"
    echo "[+] Number of extra backups       : $EXTRA_BACKUPS_NUMBER"

    if [ $EXTRA_BACKUPS_NUMBER -gt 0 ]; then
      export EXTRA_BACKUPS=$(mc find $MINIO_PG_BACKUPS_DIR -name "*.sql.gz" | sort | head --lines=$EXTRA_BACKUPS_NUMBER)
      echo "[+] Extra backups: $EXTRA_BACKUPS"
      echo "[+] Deleting them"
      mc rm $EXTRA_BACKUPS
    fi

    echo "[+] Finished"
{{ end }}
