{{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "21" ) }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: waldur-cleanup-cronjob
spec:
  schedule: "0 5 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: waldur-cleanup
              image: {{ .Values.global.imageRegistry }}/{{ .Values.waldur.imageName }}:{{ .Values.waldur.imageTag }}
              imagePullPolicy: {{ .Values.waldur.pullPolicy }}
              args:
                - waldur-cleanup
              env:
                {{- include "waldur.credentials" . | nindent 17 }}
              volumeMounts:
                - name: waldur-cleanup-script
                  mountPath: /usr/local/bin/waldur-cleanup
                  subPath: waldur-cleanup
          volumes:
            - name: waldur-cleanup-script
              configMap:
                name: waldur-cleanup-script-config
                defaultMode: 0755
          restartPolicy: Never
