{{ if and (.Values.postgresBackup.enabled) }}
{{- if or ( gt .Capabilities.KubeVersion.Major "1" ) ( ge .Capabilities.KubeVersion.Minor "21" ) }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: waldur-db-backup-rotation-cronjob
spec:
  schedule: {{ .Values.postgresBackup.rotationSchedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: "postgres-backup-cronjob"
              image: {{ .Values.global.imageRegistry }}/{{ .Values.postgresBackup.image }}
              command: ["/bin/sh"]
              args: ["-c", "backup-rotation"]
              env:
                {{ include "waldur.env.initdb" . | nindent 16 }}
                - name: MINIO_SERVER
                  value: {{ .Values.minio.endpoint | quote }}
                - name: MINIO_ACCESS_KEY
                  value: {{ .Values.minio.accessKey | quote }}
                - name: MINIO_SECRET_KEY
                  value: {{ .Values.minio.secretKey | quote }}
                - name: MINIO_BUCKET
                  value: {{ .Values.minio.bucketName | quote }}
                - name: MINIO_API_VERSION
                  value: "S3v4"
              volumeMounts:
                - name: postgres-backup-rotation-script
                  mountPath: /usr/local/bin/backup-rotation
                  subPath: backup-rotation
          volumes:
            - name: postgres-backup-rotation-script
              configMap:
                name: waldur-db-backup-rotation-script
                defaultMode: 0755
          restartPolicy: Never
{{ end }}
