apiVersion: apps/v1
kind: Deployment
metadata:
  name: waldur-homeport
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  replicas: {{ default 1 .Values.replicaCount.homeport }}
  selector:
    matchLabels:
      app: waldur-homeport
  template:
    metadata:
      labels:
        app: waldur-homeport
        {{ include "waldur.labels" . | nindent 8 }}
    spec:
      {{ if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range $i, $val := .Values.imagePullSecrets }}
        - name: {{ $val }}
        {{ end -}}
      {{ end }}
      {{ if .Values.hostAliases }}
      hostAliases:
        {{ toYaml .Values.hostAliases | nindent 8 }}
      {{ end }}
      containers:
        - name: waldur-homeport
          image: {{ .Values.global.imageRegistry }}/{{ .Values.waldur.homeport.imageName }}:{{ .Values.waldur.imageTag }}
          imagePullPolicy: {{ .Values.waldur.pullPolicy }}
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 3
            periodSeconds: 3
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: TITLE
              value: {{ .Values.waldur.whitelabeling.shortPageTitle }}
            - name: API_URL
              value: {{ printf "%s://%s/" .Values.apiScheme .Values.apiHostname | quote }}
            {{ if has "billing" .Values.waldur.features }}
            - name: ACCOUNTING_MODE
              value: 'billing'
            {{ end }}
            {{ if has "secure_session" .Values.waldur.features }}
            - name: AUTH_STORAGE
              value: 'sessionStorage'
            {{ end }}
          resources:
            {{- toYaml .Values.homeportResources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
