{{ if .Values.ingress.tls.source | eq "letsEncrypt" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.waldur.site.email }}
    privateKeySecretRef:
      name: letsencrypt-prod-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx
{{ end }}
