apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waldur-postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 10Gi
