apiVersion: v1
kind: Secret
metadata:
  name: waldur-secret
type: Opaque
data:
{{ if .Values.waldur.secretKey }}
  GLOBAL_SECRET_KEY: {{ .Values.waldur.secretKey | b64enc | quote }}
{{ end }}
{{ if and .Values.readonlyDB.enabled .Values.readonlyDB.username }}
  READONLY_DB_USERNAME: {{ .Values.readonlyDB.username | b64enc | quote }}
{{ end }}
{{ if and .Values.readonlyDB.enabled .Values.readonlyDB.password }}
  READONLY_DB_PASSWORD: {{ .Values.readonlyDB.password | b64enc | quote }}
{{ end }}
{{ if .Values.waldur.supportToken }}
  WALDUR_SUPPORT_API_TOKEN: {{ .Values.waldur.supportToken | b64enc | quote }}
{{ end }}
{{ if .Values.waldur.staffToken }}
  WALDUR_STAFF_API_TOKEN: {{ .Values.waldur.staffToken | b64enc | quote }}
{{ end }}
{{ if .Values.waldur.uvkEverypay.everypayUsername }}
  EVERYPAY_USERNAME: {{ .Values.waldur.uvkEverypay.everypayUsername | b64enc | quote }}
{{ end }}
{{ if .Values.waldur.uvkEverypay.everypayPassword }}
  EVERYPAY_PASSWORD: {{ .Values.waldur.uvkEverypay.everypayPassword | b64enc | quote }}
{{ end }}
{{ if .Values.waldur.mail.username }}
  MAIL_USER: {{ .Values.waldur.mail.username | b64enc | quote }}
{{ end }}
{{ if .Values.waldur.mail.password }}
  MAIL_PASSWORD: {{ .Values.waldur.mail.password | b64enc | quote }}
{{ end }}
{{ if .Values.waldur.pid_datacite.password }}
  DATACITE_PASSWORD: {{ .Values.waldur.pid_datacite.password | b64enc | quote }}
{{ end }}
{{ if .Values.rabbitmq.auth.username }}
  RABBITMQ_USER: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
{{ end }}
{{ if .Values.rabbitmq.auth.password }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
{{ end }}
