{{ if has "VALIMO" .Values.waldur.authMethods }}
apiVersion: v1
kind: Secret
metadata:
  name: waldur-valimo-secret
type: Opaque
data:
{{ $certsDirTemp := .Values.waldur.valimo.dir | printf "%s/valimo-client.crt" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}
{{ $certsDirTemp := .Values.waldur.valimo.dir | printf "%s/valimo-client.key" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}

{{ end }}
