apiVersion: v1
kind: Secret
metadata:
  name: pgpass
type: Opaque
data:
  {{ $host := include "waldur.postgresql.host"   . }}
  {{ $port := include "waldur.postgresql.port"   . }}
  {{ $db   := include "waldur.postgresql.dbname" . }}
  {{ $user := include "waldur.postgresql.user"   . }}

  {{ $password :=  .Values.postgresql.postgresqlPassword | quote }}
  {{ if index .Values "postgresql-ha" "enabled" }}
  {{ $password = index .Values "postgresql-ha" "postgresql" "password" | quote }}
  {{ end }}
  
  pgpass: {{ printf "%s:%s:%s:%s:%s" $host $port $db $user $password | b64enc }}
