{{ if has "SAML2" .Values.waldur.authMethods }}
apiVersion: v1
kind: Secret
metadata:
  name: waldur-saml2-secret
type: Opaque
data:
{{ $certsDirTemp := .Values.waldur.saml2.dir | printf "%s/credentials/sp.crt" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}
{{ $certsDirTemp = .Values.waldur.saml2.dir | printf "%s/credentials/sp.pem" }}
{{ (.Files.Glob $certsDirTemp).AsSecrets | indent 2 }}
{{ end }}
