{{ if .Values.postgresBackup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pgpass
type: Opaque
data:
  {{ $host := include "waldur.postgresql.host"   . | trimAll "\"" }}
  {{ $port := include "waldur.postgresql.port"   . | trimAll "\"" }}
  {{ $db   := include "waldur.postgresql.dbname" . | trimAll "\"" }}
  {{ $user := include "waldur.postgresql.user"   . | trimAll "\"" }}

  {{ $password :=  .Values.postgresql.postgresqlPassword }}
  {{ if index .Values "postgresql-ha" "enabled" }}
  {{ $password = index .Values "postgresql-ha" "postgresql" "password" }}
  {{ end }}
  
  pgpass: {{ printf "%s:%s:%s:%s:%s" $host $port $db $user $password | b64enc }}
{{ end }}
