{{ if .Values.waldur.uvkEverypay.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: waldur-uvk-everypay
  labels:
{{ include "waldur.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: waldur-uvk-everypay
{{ end }}
