{{- if and .Values.ingress.enabled (eq .Values.ingress.className "traefik") }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-admin-redirect-https
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-admin-cors
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    accessControlAllowHeaders:
      - DNT
      - Keep-Alive
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Range
      - Authorization
      - sentry-trace
      - baggage
      - X-Impersonated-User-Uuid
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true
---
{{- $whitelistRange := .Values.ingress.whitelistSourceRangeAdmin | default .Values.ingress.whitelistSourceRange }}
{{- if $whitelistRange }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-admin-ipallowlist
spec:
  ipAllowList:
    sourceRange:
      {{- range (splitList "," $whitelistRange) }}
      - {{ . | trim | quote }}
      {{- end }}
---
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-admin-chain
spec:
  chain:
    middlewares:
      - name: api-admin-redirect-https
      - name: api-admin-cors
      {{- if $whitelistRange }}
      - name: api-admin-ipallowlist
      {{- end }}
{{- end }}
