dependencies:
  - name: postgresql
    version: 9.8.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: postgresql-ha
    version: 3.9.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql-ha.enabled
